BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Message" (
	"ID_MESSAGE"	INTEGER NOT NULL,
	"CONTENT"   	string(255) NOT NULL,
	PRIMARY KEY("ID_MESSAGE" AUTOINCREMENT)
);
CREATE INDEX IF NOT EXISTS "Message_ID_MESSAGE_index" ON "Message" (
	"ID_MESSAGE"
);
COMMIT;
